### ISSUE TITLE
Id of output div

### ISSUE THREAD

**Issue by nuest** [52North/wps-js#77]
https://github.com/52North/wps-js/blob/ba29e35a17f790c57a669acc517ce1a7901d1d68/src/main/webapp/js/wps-js/form/FormBuilder.js#L148

`var outputContainer = jQuery('<div id="input"></div>');` should probably be `var outputContainer = jQuery('<div id="output"></div>');`

**Comment by ashu8912** [comment]
is the file system changed now coz i can't find this file.

**Comment by bpross-52n** [comment]
Sorry, this was an outdated issue.
